package barcode

// QRVersion : QR barcode version. Subset of https://reference.aspose.com/barcode/net/aspose.barcode.generation/qrversion/ MicroQR versions (VersionM1–VersionM4) are omitted; use Aspose.BarCode.Cloud.DTO.Enums.MicroQRVersion instead.
type QRVersion string

// List of QRVersion
const (
	QRVersionAuto      QRVersion = "Auto"
	QRVersionVersion01 QRVersion = "Version01"
	QRVersionVersion02 QRVersion = "Version02"
	QRVersionVersion03 QRVersion = "Version03"
	QRVersionVersion04 QRVersion = "Version04"
	QRVersionVersion05 QRVersion = "Version05"
	QRVersionVersion06 QRVersion = "Version06"
	QRVersionVersion07 QRVersion = "Version07"
	QRVersionVersion08 QRVersion = "Version08"
	QRVersionVersion09 QRVersion = "Version09"
	QRVersionVersion10 QRVersion = "Version10"
	QRVersionVersion11 QRVersion = "Version11"
	QRVersionVersion12 QRVersion = "Version12"
	QRVersionVersion13 QRVersion = "Version13"
	QRVersionVersion14 QRVersion = "Version14"
	QRVersionVersion15 QRVersion = "Version15"
	QRVersionVersion16 QRVersion = "Version16"
	QRVersionVersion17 QRVersion = "Version17"
	QRVersionVersion18 QRVersion = "Version18"
	QRVersionVersion19 QRVersion = "Version19"
	QRVersionVersion20 QRVersion = "Version20"
	QRVersionVersion21 QRVersion = "Version21"
	QRVersionVersion22 QRVersion = "Version22"
	QRVersionVersion23 QRVersion = "Version23"
	QRVersionVersion24 QRVersion = "Version24"
	QRVersionVersion25 QRVersion = "Version25"
	QRVersionVersion26 QRVersion = "Version26"
	QRVersionVersion27 QRVersion = "Version27"
	QRVersionVersion28 QRVersion = "Version28"
	QRVersionVersion29 QRVersion = "Version29"
	QRVersionVersion30 QRVersion = "Version30"
	QRVersionVersion31 QRVersion = "Version31"
	QRVersionVersion32 QRVersion = "Version32"
	QRVersionVersion33 QRVersion = "Version33"
	QRVersionVersion34 QRVersion = "Version34"
	QRVersionVersion35 QRVersion = "Version35"
	QRVersionVersion36 QRVersion = "Version36"
	QRVersionVersion37 QRVersion = "Version37"
	QRVersionVersion38 QRVersion = "Version38"
	QRVersionVersion39 QRVersion = "Version39"
	QRVersionVersion40 QRVersion = "Version40"
)
