package barcode

// QrVersion :
type QrVersion string

// List of QRVersion
const (
	QrVersionAuto      QrVersion = "Auto"
	QrVersionVersion01 QrVersion = "Version01"
	QrVersionVersion02 QrVersion = "Version02"
	QrVersionVersion03 QrVersion = "Version03"
	QrVersionVersion04 QrVersion = "Version04"
	QrVersionVersion05 QrVersion = "Version05"
	QrVersionVersion06 QrVersion = "Version06"
	QrVersionVersion07 QrVersion = "Version07"
	QrVersionVersion08 QrVersion = "Version08"
	QrVersionVersion09 QrVersion = "Version09"
	QrVersionVersion10 QrVersion = "Version10"
	QrVersionVersion11 QrVersion = "Version11"
	QrVersionVersion12 QrVersion = "Version12"
	QrVersionVersion13 QrVersion = "Version13"
	QrVersionVersion14 QrVersion = "Version14"
	QrVersionVersion15 QrVersion = "Version15"
	QrVersionVersion16 QrVersion = "Version16"
	QrVersionVersion17 QrVersion = "Version17"
	QrVersionVersion18 QrVersion = "Version18"
	QrVersionVersion19 QrVersion = "Version19"
	QrVersionVersion20 QrVersion = "Version20"
	QrVersionVersion21 QrVersion = "Version21"
	QrVersionVersion22 QrVersion = "Version22"
	QrVersionVersion23 QrVersion = "Version23"
	QrVersionVersion24 QrVersion = "Version24"
	QrVersionVersion25 QrVersion = "Version25"
	QrVersionVersion26 QrVersion = "Version26"
	QrVersionVersion27 QrVersion = "Version27"
	QrVersionVersion28 QrVersion = "Version28"
	QrVersionVersion29 QrVersion = "Version29"
	QrVersionVersion30 QrVersion = "Version30"
	QrVersionVersion31 QrVersion = "Version31"
	QrVersionVersion32 QrVersion = "Version32"
	QrVersionVersion33 QrVersion = "Version33"
	QrVersionVersion34 QrVersion = "Version34"
	QrVersionVersion35 QrVersion = "Version35"
	QrVersionVersion36 QrVersion = "Version36"
	QrVersionVersion37 QrVersion = "Version37"
	QrVersionVersion38 QrVersion = "Version38"
	QrVersionVersion39 QrVersion = "Version39"
	QrVersionVersion40 QrVersion = "Version40"
	QrVersionVersionM1 QrVersion = "VersionM1"
	QrVersionVersionM2 QrVersion = "VersionM2"
	QrVersionVersionM3 QrVersion = "VersionM3"
	QrVersionVersionM4 QrVersion = "VersionM4"
)
