/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud
// AztecSymbolMode : 
type AztecSymbolMode string

// List of AztecSymbolMode
const (
	AUTO_AztecSymbolMode AztecSymbolMode = "Auto"
	COMPACT_AztecSymbolMode AztecSymbolMode = "Compact"
	FULL_RANGE_AztecSymbolMode AztecSymbolMode = "FullRange"
	RUNE__AztecSymbolMode AztecSymbolMode = "Rune"
)
