/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud
// CodeLocation : 
type CodeLocation string

// List of CodeLocation
const (
	BELOW_CodeLocation CodeLocation = "Below"
	ABOVE_CodeLocation CodeLocation = "Above"
	NONE_CodeLocation CodeLocation = "None"
)
