/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud

// Padding around barcode.             
type Padding struct {
	// Left padding.             
	Left float64 `json:"Left,omitempty"`
	// Right padding.             
	Right float64 `json:"Right,omitempty"`
	// Top padding.             
	Top float64 `json:"Top,omitempty"`
	// Bottom padding.             
	Bottom float64 `json:"Bottom,omitempty"`
}
