/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud

// QrEncodeMode :
type QrEncodeMode string

// List of QREncodeMode
const (
	AUTO_QrEncodeMode              QrEncodeMode = "Auto"
	BYTES_QrEncodeMode             QrEncodeMode = "Bytes"
	UTF8_BOM_QrEncodeMode          QrEncodeMode = "Utf8BOM"
	UTF16_BEBOM_QrEncodeMode       QrEncodeMode = "Utf16BEBOM"
	ECI_ENCODING_QrEncodeMode      QrEncodeMode = "ECIEncoding"
	EXTENDED_CODETEXT_QrEncodeMode QrEncodeMode = "ExtendedCodetext"
)
