/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud

// CodabarSymbol :
type CodabarSymbol string

// List of CodabarSymbol
const (
	A_CodabarSymbol CodabarSymbol = "A"
	B_CodabarSymbol CodabarSymbol = "B"
	C_CodabarSymbol CodabarSymbol = "C"
	D_CodabarSymbol CodabarSymbol = "D"
)
