/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud

// Error
type ModelError struct {
	// Code             
	Code string `json:"Code,omitempty"`
	// Message             
	Message string `json:"Message,omitempty"`
	// Description             
	Description string `json:"Description,omitempty"`
	// Inner Error             
	InnerError *ErrorDetails `json:"InnerError,omitempty"`
}
