/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud

// QrEncodeType :
type QrEncodeType string

// List of QREncodeType
const (
	AUTO_QrEncodeType           QrEncodeType = "Auto"
	FORCE_QR_QrEncodeType       QrEncodeType = "ForceQR"
	FORCE_MICRO_QR_QrEncodeType QrEncodeType = "ForceMicroQR"
)
