/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud

// QrVersion :
type QrVersion string

// List of QRVersion
const (
	AUTO_QrVersion       QrVersion = "Auto"
	VERSION01_QrVersion  QrVersion = "Version01"
	VERSION02_QrVersion  QrVersion = "Version02"
	VERSION03_QrVersion  QrVersion = "Version03"
	VERSION04_QrVersion  QrVersion = "Version04"
	VERSION05_QrVersion  QrVersion = "Version05"
	VERSION06_QrVersion  QrVersion = "Version06"
	VERSION07_QrVersion  QrVersion = "Version07"
	VERSION08_QrVersion  QrVersion = "Version08"
	VERSION09_QrVersion  QrVersion = "Version09"
	VERSION10_QrVersion  QrVersion = "Version10"
	VERSION11_QrVersion  QrVersion = "Version11"
	VERSION12_QrVersion  QrVersion = "Version12"
	VERSION13_QrVersion  QrVersion = "Version13"
	VERSION14_QrVersion  QrVersion = "Version14"
	VERSION15_QrVersion  QrVersion = "Version15"
	VERSION16_QrVersion  QrVersion = "Version16"
	VERSION17_QrVersion  QrVersion = "Version17"
	VERSION18_QrVersion  QrVersion = "Version18"
	VERSION19_QrVersion  QrVersion = "Version19"
	VERSION20_QrVersion  QrVersion = "Version20"
	VERSION21_QrVersion  QrVersion = "Version21"
	VERSION22_QrVersion  QrVersion = "Version22"
	VERSION23_QrVersion  QrVersion = "Version23"
	VERSION24_QrVersion  QrVersion = "Version24"
	VERSION25_QrVersion  QrVersion = "Version25"
	VERSION26_QrVersion  QrVersion = "Version26"
	VERSION27_QrVersion  QrVersion = "Version27"
	VERSION28_QrVersion  QrVersion = "Version28"
	VERSION29_QrVersion  QrVersion = "Version29"
	VERSION30_QrVersion  QrVersion = "Version30"
	VERSION31_QrVersion  QrVersion = "Version31"
	VERSION32_QrVersion  QrVersion = "Version32"
	VERSION33_QrVersion  QrVersion = "Version33"
	VERSION34_QrVersion  QrVersion = "Version34"
	VERSION35_QrVersion  QrVersion = "Version35"
	VERSION36_QrVersion  QrVersion = "Version36"
	VERSION37_QrVersion  QrVersion = "Version37"
	VERSION38_QrVersion  QrVersion = "Version38"
	VERSION39_QrVersion  QrVersion = "Version39"
	VERSION40_QrVersion  QrVersion = "Version40"
	VERSION_M1_QrVersion QrVersion = "VersionM1"
	VERSION_M2_QrVersion QrVersion = "VersionM2"
	VERSION_M3_QrVersion QrVersion = "VersionM3"
	VERSION_M4_QrVersion QrVersion = "VersionM4"
)
