/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud

// Codabar parameters.
type CodabarParams struct {
	// Checksum algorithm for Codabar barcodes. Default value: CodabarChecksumMode.Mod16. To enable checksum calculation set value EnableChecksum.Yes to property EnableChecksum.
	ChecksumMode *CodabarChecksumMode `json:"ChecksumMode,omitempty"`
	// Start symbol (character) of Codabar symbology. Default value: CodabarSymbol.A
	StartSymbol *CodabarSymbol `json:"StartSymbol,omitempty"`
	// Stop symbol (character) of Codabar symbology. Default value: CodabarSymbol.A
	StopSymbol *CodabarSymbol `json:"StopSymbol,omitempty"`
}
