/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud

import (
	"time"
)

// The error details
type ErrorDetails struct {
	// The request id
	RequestId string `json:"RequestId,omitempty"`
	// Date
	Date time.Time `json:"Date"`
}
