/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud
// CodabarChecksumMode : 
type CodabarChecksumMode string

// List of CodabarChecksumMode
const (
	MOD10_CodabarChecksumMode CodabarChecksumMode = "Mod10"
	MOD16_CodabarChecksumMode CodabarChecksumMode = "Mod16"
)
