/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud
// FontStyle : 
type FontStyle string

// List of FontStyle
const (
	REGULAR_FontStyle FontStyle = "Regular"
	BOLD_FontStyle FontStyle = "Bold"
	ITALIC_FontStyle FontStyle = "Italic"
	UNDERLINE_FontStyle FontStyle = "Underline"
	STRIKEOUT_FontStyle FontStyle = "Strikeout"
)
