/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud
// AvailableGraphicsUnit : Subset of GraphicsUnit.             
type AvailableGraphicsUnit string

// List of AvailableGraphicsUnit
const (
	PIXEL_AvailableGraphicsUnit AvailableGraphicsUnit = "Pixel"
	POINT_AvailableGraphicsUnit AvailableGraphicsUnit = "Point"
	INCH_AvailableGraphicsUnit AvailableGraphicsUnit = "Inch"
	MILLIMETER_AvailableGraphicsUnit AvailableGraphicsUnit = "Millimeter"
)
