/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud

// PDF417 parameters.             
type Pdf417Params struct {
	// Height/Width ratio of 2D BarCode module.             
	AspectRatio float64 `json:"AspectRatio,omitempty"`
	// Encoding of codetext.             
	TextEncoding string `json:"TextEncoding,omitempty"`
	// Columns count.             
	Columns int32 `json:"Columns,omitempty"`
	// Pdf417 symbology type of BarCode's compaction mode. Default value: Pdf417CompactionMode.Auto.
	CompactionMode *Pdf417CompactionMode `json:"CompactionMode,omitempty"`
	// Pdf417 symbology type of BarCode's error correction level ranging from level0 to level8, level0 means no error correction info, level8 means best error correction which means a larger picture.
	ErrorLevel *Pdf417ErrorLevel `json:"ErrorLevel,omitempty"`
	// Macro Pdf417 barcode's file ID. Used for MacroPdf417.
	MacroFileID int32 `json:"MacroFileID,omitempty"`
	// Macro Pdf417 barcode's segment ID, which starts from 0, to MacroSegmentsCount - 1.
	MacroSegmentID int32 `json:"MacroSegmentID,omitempty"`
	// Macro Pdf417 barcode segments count.
	MacroSegmentsCount int32 `json:"MacroSegmentsCount,omitempty"`
	// Rows count.
	Rows int32 `json:"Rows,omitempty"`
	// Whether Pdf417 symbology type of BarCode is truncated (to reduce space).
	Truncate bool `json:"Truncate,omitempty"`
}
