/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud
// CustomerInformationInterpretingType : 
type CustomerInformationInterpretingType string

// List of CustomerInformationInterpretingType
const (
	C_TABLE_CustomerInformationInterpretingType CustomerInformationInterpretingType = "CTable"
	N_TABLE_CustomerInformationInterpretingType CustomerInformationInterpretingType = "NTable"
	OTHER_CustomerInformationInterpretingType CustomerInformationInterpretingType = "Other"
)
