/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud

// AutoSizeMode :
type AutoSizeMode string

// List of AutoSizeMode
const (
	NONE_AutoSizeMode          AutoSizeMode = "None"
	NEAREST_AutoSizeMode       AutoSizeMode = "Nearest"
	INTERPOLATION_AutoSizeMode AutoSizeMode = "Interpolation"
)
