/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud

// Wrapper around Drawing.Point for proper specification.             
type RegionPoint struct {
	// X-coordinate             
	X int32 `json:"X"`
	// Y-coordinate             
	Y int32 `json:"Y"`
}
