/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud
// EnableChecksum : 
type EnableChecksum string

// List of EnableChecksum
const (
	DEFAULT__EnableChecksum EnableChecksum = "Default"
	YES_EnableChecksum EnableChecksum = "Yes"
	NO_EnableChecksum EnableChecksum = "No"
)
