/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud

// DataMatrix parameters.
type DataMatrixParams struct {
	// Height/Width ratio of 2D BarCode module
	AspectRatio float64 `json:"AspectRatio,omitempty"`
	// Encoding of codetext.
	TextEncoding string `json:"TextEncoding,omitempty"`
	// Columns count.
	Columns int32 `json:"Columns,omitempty"`
	// Datamatrix ECC type. Default value: DataMatrixEccType.Ecc200.
	DataMatrixEcc *DataMatrixEccType `json:"DataMatrixEcc,omitempty"`
	// Encode mode of Datamatrix barcode. Default value: DataMatrixEncodeMode.Auto.
	DataMatrixEncodeMode *DataMatrixEncodeMode `json:"DataMatrixEncodeMode,omitempty"`
	// Rows count.
	Rows int32 `json:"Rows,omitempty"`
}
