/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud

// QrErrorLevel :
type QrErrorLevel string

// List of QRErrorLevel
const (
	LEVEL_L_QrErrorLevel QrErrorLevel = "LevelL"
	LEVEL_M_QrErrorLevel QrErrorLevel = "LevelM"
	LEVEL_Q_QrErrorLevel QrErrorLevel = "LevelQ"
	LEVEL_H_QrErrorLevel QrErrorLevel = "LevelH"
)
