/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud
// EciEncodings : 
type EciEncodings string

// List of ECIEncodings
const (
	ISO_8859_1_EciEncodings EciEncodings = "ISO_8859_1"
	ISO_8859_2_EciEncodings EciEncodings = "ISO_8859_2"
	ISO_8859_3_EciEncodings EciEncodings = "ISO_8859_3"
	ISO_8859_4_EciEncodings EciEncodings = "ISO_8859_4"
	ISO_8859_5_EciEncodings EciEncodings = "ISO_8859_5"
	ISO_8859_6_EciEncodings EciEncodings = "ISO_8859_6"
	ISO_8859_7_EciEncodings EciEncodings = "ISO_8859_7"
	ISO_8859_8_EciEncodings EciEncodings = "ISO_8859_8"
	ISO_8859_9_EciEncodings EciEncodings = "ISO_8859_9"
	ISO_8859_10_EciEncodings EciEncodings = "ISO_8859_10"
	ISO_8859_11_EciEncodings EciEncodings = "ISO_8859_11"
	ISO_8859_13_EciEncodings EciEncodings = "ISO_8859_13"
	ISO_8859_14_EciEncodings EciEncodings = "ISO_8859_14"
	ISO_8859_15_EciEncodings EciEncodings = "ISO_8859_15"
	ISO_8859_16_EciEncodings EciEncodings = "ISO_8859_16"
	SHIFT_JIS_EciEncodings EciEncodings = "Shift_JIS"
	WIN1250_EciEncodings EciEncodings = "Win1250"
	WIN1251_EciEncodings EciEncodings = "Win1251"
	WIN1252_EciEncodings EciEncodings = "Win1252"
	WIN1256_EciEncodings EciEncodings = "Win1256"
	UTF16_BE_EciEncodings EciEncodings = "UTF16BE"
	UTF8_EciEncodings EciEncodings = "UTF8"
	US_ASCII_EciEncodings EciEncodings = "US_ASCII"
	BIG5_EciEncodings EciEncodings = "Big5"
	GB18030_EciEncodings EciEncodings = "GB18030"
	EUC_KR_EciEncodings EciEncodings = "EUC_KR"
)
