/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud
// BorderDashStyle : 
type BorderDashStyle string

// List of BorderDashStyle
const (
	SOLID_BorderDashStyle BorderDashStyle = "Solid"
	DASH_BorderDashStyle BorderDashStyle = "Dash"
	DOT_BorderDashStyle BorderDashStyle = "Dot"
	DASH_DOT_BorderDashStyle BorderDashStyle = "DashDot"
	DASH_DOT_DOT_BorderDashStyle BorderDashStyle = "DashDotDot"
)
