/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud
// Pdf417ErrorLevel : 
type Pdf417ErrorLevel string

// List of Pdf417ErrorLevel
const (
	LEVEL0_Pdf417ErrorLevel Pdf417ErrorLevel = "Level0"
	LEVEL1_Pdf417ErrorLevel Pdf417ErrorLevel = "Level1"
	LEVEL2_Pdf417ErrorLevel Pdf417ErrorLevel = "Level2"
	LEVEL3_Pdf417ErrorLevel Pdf417ErrorLevel = "Level3"
	LEVEL4_Pdf417ErrorLevel Pdf417ErrorLevel = "Level4"
	LEVEL5_Pdf417ErrorLevel Pdf417ErrorLevel = "Level5"
	LEVEL6_Pdf417ErrorLevel Pdf417ErrorLevel = "Level6"
	LEVEL7_Pdf417ErrorLevel Pdf417ErrorLevel = "Level7"
	LEVEL8_Pdf417ErrorLevel Pdf417ErrorLevel = "Level8"
)
