/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud

// Represents information about barcode list.
type BarcodeResponseList struct {
	// List of barcodes which are present in image.
	Barcodes []BarcodeResponse `json:"Barcodes,omitempty"`
}
