/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud

// Databar parameters.
type DataBarParams struct {
	// Height/Width ratio of 2D BarCode module. Used for DataBar stacked.
	AspectRatio float64 `json:"AspectRatio,omitempty"`
	// Columns count.
	Columns int32 `json:"Columns,omitempty"`
	// Rows count.
	Rows int32 `json:"Rows,omitempty"`
}
