/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud

// ChecksumValidation :
type ChecksumValidation string

// List of ChecksumValidation
const (
	DEFAULT__ChecksumValidation ChecksumValidation = "Default"
	ON_ChecksumValidation       ChecksumValidation = "On"
	OFF_ChecksumValidation      ChecksumValidation = "Off"
)
