/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud

// Represents information about barcode.
type BarcodeResponse struct {
	// Barcode data.
	BarcodeValue string `json:"BarcodeValue,omitempty"`
	// Type of the barcode.
	Type_ string `json:"Type,omitempty"`
	// Region with barcode.
	Region []RegionPoint `json:"Region,omitempty"`
	// Checksum of barcode.
	Checksum string `json:"Checksum,omitempty"`
}
