/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud

// DataMatrixEncodeMode :
type DataMatrixEncodeMode string

// List of DataMatrixEncodeMode
const (
	AUTO_DataMatrixEncodeMode   DataMatrixEncodeMode = "Auto"
	ASCII_DataMatrixEncodeMode  DataMatrixEncodeMode = "ASCII"
	FULL_DataMatrixEncodeMode   DataMatrixEncodeMode = "Full"
	CUSTOM_DataMatrixEncodeMode DataMatrixEncodeMode = "Custom"
	C40_DataMatrixEncodeMode    DataMatrixEncodeMode = "C40"
	TEXT_DataMatrixEncodeMode   DataMatrixEncodeMode = "Text"
)
