/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud

// Itf14BorderType :
type Itf14BorderType string

// List of ITF14BorderType
const (
	NONE_Itf14BorderType      Itf14BorderType = "None"
	FRAME_Itf14BorderType     Itf14BorderType = "Frame"
	BAR_Itf14BorderType       Itf14BorderType = "Bar"
	FRAME_OUT_Itf14BorderType Itf14BorderType = "FrameOut"
	BAR_OUT_Itf14BorderType   Itf14BorderType = "BarOut"
)
