/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud
// DecodeBarcodeType : See DecodeType             
type DecodeBarcodeType string

// List of DecodeBarcodeType
const (
	ALL_DecodeBarcodeType DecodeBarcodeType = "all"
	AUSTRALIA_POST_DecodeBarcodeType DecodeBarcodeType = "AustraliaPost"
	AZTEC_DecodeBarcodeType DecodeBarcodeType = "Aztec"
	ISBN_DecodeBarcodeType DecodeBarcodeType = "ISBN"
	CODABAR_DecodeBarcodeType DecodeBarcodeType = "Codabar"
	CODE11_DecodeBarcodeType DecodeBarcodeType = "Code11"
	CODE128_DecodeBarcodeType DecodeBarcodeType = "Code128"
	GS1_CODE128_DecodeBarcodeType DecodeBarcodeType = "GS1Code128"
	CODE39_EXTENDED_DecodeBarcodeType DecodeBarcodeType = "Code39Extended"
	CODE39_STANDARD_DecodeBarcodeType DecodeBarcodeType = "Code39Standard"
	CODE93_EXTENDED_DecodeBarcodeType DecodeBarcodeType = "Code93Extended"
	CODE93_STANDARD_DecodeBarcodeType DecodeBarcodeType = "Code93Standard"
	DATA_MATRIX_DecodeBarcodeType DecodeBarcodeType = "DataMatrix"
	DEUTSCHE_POST_IDENTCODE_DecodeBarcodeType DecodeBarcodeType = "DeutschePostIdentcode"
	DEUTSCHE_POST_LEITCODE_DecodeBarcodeType DecodeBarcodeType = "DeutschePostLeitcode"
	EAN13_DecodeBarcodeType DecodeBarcodeType = "EAN13"
	EAN14_DecodeBarcodeType DecodeBarcodeType = "EAN14"
	EAN8_DecodeBarcodeType DecodeBarcodeType = "EAN8"
	IATA2OF5_DecodeBarcodeType DecodeBarcodeType = "IATA2of5"
	INTERLEAVED2OF5_DecodeBarcodeType DecodeBarcodeType = "Interleaved2of5"
	ISSN_DecodeBarcodeType DecodeBarcodeType = "ISSN"
	ISMN_DecodeBarcodeType DecodeBarcodeType = "ISMN"
	ITALIAN_POST25_DecodeBarcodeType DecodeBarcodeType = "ItalianPost25"
	ITF14_DecodeBarcodeType DecodeBarcodeType = "ITF14"
	ITF6_DecodeBarcodeType DecodeBarcodeType = "ITF6"
	MACRO_PDF417_DecodeBarcodeType DecodeBarcodeType = "MacroPdf417"
	MATRIX2OF5_DecodeBarcodeType DecodeBarcodeType = "Matrix2of5"
	MSI_DecodeBarcodeType DecodeBarcodeType = "MSI"
	ONE_CODE_DecodeBarcodeType DecodeBarcodeType = "OneCode"
	OPC_DecodeBarcodeType DecodeBarcodeType = "OPC"
	PATCH_CODE_DecodeBarcodeType DecodeBarcodeType = "PatchCode"
	PDF417_DecodeBarcodeType DecodeBarcodeType = "Pdf417"
	MICRO_PDF417_DecodeBarcodeType DecodeBarcodeType = "MicroPdf417"
	PLANET_DecodeBarcodeType DecodeBarcodeType = "Planet"
	POSTNET_DecodeBarcodeType DecodeBarcodeType = "Postnet"
	PZN_DecodeBarcodeType DecodeBarcodeType = "PZN"
	QR_DecodeBarcodeType DecodeBarcodeType = "QR"
	MICRO_QR_DecodeBarcodeType DecodeBarcodeType = "MicroQR"
	RM4_SCC_DecodeBarcodeType DecodeBarcodeType = "RM4SCC"
	SCC14_DecodeBarcodeType DecodeBarcodeType = "SCC14"
	SSCC18_DecodeBarcodeType DecodeBarcodeType = "SSCC18"
	STANDARD2OF5_DecodeBarcodeType DecodeBarcodeType = "Standard2of5"
	SUPPLEMENT_DecodeBarcodeType DecodeBarcodeType = "Supplement"
	UPCA_DecodeBarcodeType DecodeBarcodeType = "UPCA"
	UPCE_DecodeBarcodeType DecodeBarcodeType = "UPCE"
	VIN_DecodeBarcodeType DecodeBarcodeType = "VIN"
	PHARMACODE_DecodeBarcodeType DecodeBarcodeType = "Pharmacode"
	GS1_DATA_MATRIX_DecodeBarcodeType DecodeBarcodeType = "GS1DataMatrix"
	DATABAR_OMNI_DIRECTIONAL_DecodeBarcodeType DecodeBarcodeType = "DatabarOmniDirectional"
	DATABAR_TRUNCATED_DecodeBarcodeType DecodeBarcodeType = "DatabarTruncated"
	DATABAR_LIMITED_DecodeBarcodeType DecodeBarcodeType = "DatabarLimited"
	DATABAR_EXPANDED_DecodeBarcodeType DecodeBarcodeType = "DatabarExpanded"
	SWISS_POST_PARCEL_DecodeBarcodeType DecodeBarcodeType = "SwissPostParcel"
	AUSTRALIAN_POSTE_PARCEL_DecodeBarcodeType DecodeBarcodeType = "AustralianPosteParcel"
	CODE16_K_DecodeBarcodeType DecodeBarcodeType = "Code16K"
	DATABAR_STACKED_OMNI_DIRECTIONAL_DecodeBarcodeType DecodeBarcodeType = "DatabarStackedOmniDirectional"
	DATABAR_STACKED_DecodeBarcodeType DecodeBarcodeType = "DatabarStacked"
	DATABAR_EXPANDED_STACKED_DecodeBarcodeType DecodeBarcodeType = "DatabarExpandedStacked"
	COMPACT_PDF417_DecodeBarcodeType DecodeBarcodeType = "CompactPdf417"
	GS1_QR_DecodeBarcodeType DecodeBarcodeType = "GS1QR"
	MAXI_CODE_DecodeBarcodeType DecodeBarcodeType = "MaxiCode"
	MICR_E13_B_DecodeBarcodeType DecodeBarcodeType = "MicrE13B"
	CODE32_DecodeBarcodeType DecodeBarcodeType = "Code32"
	DATA_LOGIC2OF5_DecodeBarcodeType DecodeBarcodeType = "DataLogic2of5"
	DOT_CODE_DecodeBarcodeType DecodeBarcodeType = "DotCode"
	DUTCH_KIX_DecodeBarcodeType DecodeBarcodeType = "DutchKIX"
	CODABLOCK_F_DecodeBarcodeType DecodeBarcodeType = "CodablockF"
)
