/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud

// Caption
type CaptionParams struct {
	// Caption text.
	Text string `json:"Text,omitempty"`
	// Text alignment.
	Alignment *TextAlignment `json:"Alignment,omitempty"`
	// Text color.
	Color string `json:"Color,omitempty"`
	// Is caption visible.
	Visible bool `json:"Visible,omitempty"`
	// Font.
	Font *FontParams `json:"Font,omitempty"`
	// Padding.
	Padding *Padding `json:"Padding,omitempty"`
}
