/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud

// Represents list of barcode generators
type GeneratorParamsList struct {
	// List of barcode generators
	BarcodeBuilders []GeneratorParams `json:"BarcodeBuilders,omitempty"`
	// Shift step according to X axis
	XStep int32 `json:"XStep"`
	// Shift step according to Y axis
	YStep int32 `json:"YStep"`
}
