/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud

// Font.
type FontParams struct {
	// Font family.
	Family string `json:"Family,omitempty"`
	// Font size in units.
	Size float64 `json:"Size,omitempty"`
	// Font style.
	Style *FontStyle `json:"Style,omitempty"`
}
