/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud

// Class for disc space information.
type DiscUsage struct {
	// Application used disc space.
	UsedSize int64 `json:"UsedSize"`
	// Total disc space.
	TotalSize int64 `json:"TotalSize"`
}
