/*
 * Aspose.Barcode Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose_barcode_cloud
// Pdf417CompactionMode : 
type Pdf417CompactionMode string

// List of Pdf417CompactionMode
const (
	AUTO_Pdf417CompactionMode Pdf417CompactionMode = "Auto"
	TEXT_Pdf417CompactionMode Pdf417CompactionMode = "Text"
	NUMERIC_Pdf417CompactionMode Pdf417CompactionMode = "Numeric"
	BINARY_Pdf417CompactionMode Pdf417CompactionMode = "Binary"
)
