name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # See go.mod for oldest supported version
        # And https://go.dev/dl/ for updates
        # https://github.com/actions/setup-go/#using-stableoldstable-aliases
        go-version: [ '1.17', 'oldstable', 'stable' ]
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: go.sum

      - name: Get dependencies
        run: make init

      - name: Build and Test
        run: |
         chmod +x scripts/*
         make ci
        env:
          TEST_CONFIGURATION_ACCESS_TOKEN: ${{ secrets.TEST_CONFIGURATION_ACCESS_TOKEN }}
