name: Go

on:
  push:
    branches: [ v4 ]
  pull_request:
    branches: [ v4 ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # See go.mod for oldest supported version
        # And https://go.dev/dl/ for updates
        # https://github.com/actions/setup-go/#using-stableoldstable-aliases
        go-version: [ '1.24', 'oldstable', 'stable' ]
    continue-on-error: true

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: go.sum

      - name: Get dependencies
        run: make init

      - name: Build and Test
        run: |
         chmod +x scripts/*
         make ci
        env:
          TEST_JWT_ACCESS_TOKEN: ${{ secrets.TEST_CONFIGURATION_ACCESS_TOKEN }}

  coverage:
    name: Library coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: stable
          cache-dependency-path: go.sum

      - name: Get dependencies
        run: make init

      - name: Check library coverage
        run: |
         chmod +x scripts/*
         make coverage
        env:
          TEST_JWT_ACCESS_TOKEN: ${{ secrets.TEST_CONFIGURATION_ACCESS_TOKEN }}
